# Copyright 2026 OpenStack Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add_computehost_indexes

Revision ID: 4fe5e44880da
Revises: bf2011753964
Create Date: 2026-06-04 21:33:06.515431

"""

# revision identifiers, used by Alembic.
revision = '4fe5e44880da'
down_revision = 'bf2011753964'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_computehost_allocations_compute_host_id', 'computehost_allocations', ['compute_host_id'], unique=False)
    op.create_index('ix_computehost_allocations_reservation_id', 'computehost_allocations', ['reservation_id'], unique=False)
    op.create_index('ix_computehost_extra_capabilities_computehost_id', 'computehost_extra_capabilities', ['computehost_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_computehost_extra_capabilities_computehost_id', table_name='computehost_extra_capabilities')
    op.drop_index('ix_computehost_allocations_reservation_id', table_name='computehost_allocations')
    op.drop_index('ix_computehost_allocations_compute_host_id', table_name='computehost_allocations')
    # ### end Alembic commands ###
