# Copyright 2026 OpenStack Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add_lease_indexes

Revision ID: bf2011753964
Revises: ee3b2513b59f
Create Date: 2026-06-03 19:54:19.674143

"""

# revision identifiers, used by Alembic.
revision = 'bf2011753964'
down_revision = 'ee3b2513b59f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_leases_end_date', 'leases', ['end_date'], unique=False)
    op.create_index('ix_leases_project_id', 'leases', ['project_id'], unique=False)
    op.create_index('ix_leases_status', 'leases', ['status'], unique=False)
    op.create_index('ix_leases_project_end_date', 'leases', ['project_id', 'end_date'], unique=False)
    op.create_index('ix_leases_status_end_date', 'leases', ['status', 'end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leases_status', table_name='leases')
    op.drop_index('ix_leases_project_id', table_name='leases')
    op.drop_index('ix_leases_end_date', table_name='leases')
    op.drop_index('ix_leases_status_end_date', table_name='leases')
    op.drop_index('ix_leases_project_end_date', table_name='leases')
    # ### end Alembic commands ###
