# Copyright 2023 OpenStack Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add disabled in compute host

Revision ID: d5a379ff6ba3
Revises: 4b7bdec3ae61
Create Date: 2023-11-17 10:48:50.403580

"""

# revision identifiers, used by Alembic.
revision = 'd5a379ff6ba3'
down_revision = '4b7bdec3ae61'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computehosts', sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('devices', 'device_driver',
               existing_type=mysql.ENUM('zun', 'k3s'),
               nullable=False)
    op.drop_column('network_reservations', 'vfc_resources')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_reservations', sa.Column('vfc_resources', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('devices', 'device_driver',
               existing_type=mysql.ENUM('zun', 'k3s'),
               nullable=True)
    op.drop_column('computehosts', 'disabled')
    # ### end Alembic commands ###
# Copyright 2023 OpenStack Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add disabled in compute host

Revision ID: d5a379ff6ba3
Revises: 4b7bdec3ae61
Create Date: 2023-11-17 10:48:50.403580

"""

# revision identifiers, used by Alembic.
revision = 'd5a379ff6ba3'
down_revision = '4b7bdec3ae61'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computehosts', sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('devices', 'device_driver',
               existing_type=mysql.ENUM('zun', 'k3s'),
               nullable=False)
    op.drop_column('network_reservations', 'vfc_resources')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_reservations', sa.Column('vfc_resources', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('devices', 'device_driver',
               existing_type=mysql.ENUM('zun', 'k3s'),
               nullable=True)
    op.drop_column('computehosts', 'disabled')
    # ### end Alembic commands ###
