[build-system]
requires = ["pbr>=6.0.0", "setuptools>=64.0.0"]
build-backend = "pbr.build"

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = [
    "E",        # pycodestyle (error)
    "F",        # pyflakes
    "G",        # flake8-logging-format
    "LOG",      # flake8-logging
]


ignore = [
    "E501", # line too long
    "G001", # logging statement uses str.format
    "G002", # Logging statement uses `%`
    "G004", # logging statement uses f-string
    "G010", # Logging statement uses `warn` instead of `warning`
    "E741", # Ambiguous variable name
    "F401", # imported but unused
    "E402", # many files monkeypatch eventlet, so imports not at top of file
]
