name: Unit tests

on:
  push:
    branches:
      - "chameleoncloud/*"
  pull_request:


jobs:
  run_linting:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

      
  run_tests:
    strategy:
      matrix:
        include:
          - python_version: "3.9"
            tox_env: "py39"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install tox
        run: pip install tox
      - name: Run tests
        run: tox -e ${{ matrix.tox_env }}
