name: Unit tests

on:
  push:
    branches:
      - "chameleoncloud/*"
  pull_request:


jobs:
  run_linting:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3


  run_tests:
    strategy:
      matrix:
        include:
          - python_version: "3.9"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: install uv for speedup
        run: pip install uv
      - name: install test tools
        run: |
          uv pip install \
            --system \
            -r requirements.txt \
            -r test-requirements.txt \
            .
      - name: init stestr repo
        run: stestr init
      - name: run stestr tests
        run: |
          stestr run \
          --exclude-list stestr_known_failing.txt
      - name: list failing tests
        run: stestr failing --list
        if: always() #run even if tests fail
