name: Unit tests

on: [push, pull_request]

jobs:
  unittest:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
        - "3.9"
        - "3.10"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install tox
      - run: tox -e py
